### ISSUE TITLE
Not compatible with the latest release version Version 9 - Build 238

### ISSUE THREAD

**Issue by Silveressa** [jegasus/chatlog-scaler#4]
Like the title says, it's not working with the latest version Version 9 - Build 238, any chance of an update? This is an absolutely essential mod for one of my vision impaired players to be able to play the game.

**Comment by jegasus** [comment]
Hi there! I'm happy to hear people are using my module! As for the update, I'll try to get this off the ground this weekend. I still haven't looked into V9. Hopefully it won't need too much tweaking! I'll keep you posted in this thread. Thanks again for the report!

**Comment by Silveressa** [comment]
Thanks, much appreciated!

**Comment by jegasus** [comment]
I've just released a new version of the module that makes it work for Foundry v9! Please let me know if the issues persist =)
